
    document.write("<h2>Question1</h2>");
    var username;
    document.write("<h2>Question2</h2>");
    var Name="Muneeb Farid";
    document.write("<h2>Question3</h2>");
    var message;
    message="Hello World";
    alert(message);
    document.write("<h2>Question4</h2>");
    var name="Muneeb";
    var age="24";
    var certification="Web and Mobile Hybrid app development";
    alert(name);
    alert(age+" years old");
    alert(certification);
    document.write("<h2>Question5</h2>");
    word="PIZZA";
    alert(word+"\n"+word.substring(0,4)+"\n"+word.substring(0,3)+"\n"+word.substring(0,2)+"\n"+word.substring(0,1));
    document.write("<h2>Question6</h2>");
    var email="muneebfarid28@gmail.com";
    alert("My email address is "+email);
    document.write("<h2>Question7</h2>");
    var book="A smarter way to learn JavaScript";
    alert("book");
    document.write("<h2>Question8</h2>");
    document.write("Yah! I can write HTML content Through JavaScript");
    document.write("<h2>Question9</h2>");
    var str= "▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
    alert(str);
    document.write(str);